### ISSUE TITLE
gitlab connector assigns name as username

### ISSUE THREAD

**Issue by pfijalki** [concourse/dex#7]
In
https://github.com/concourse/dex/blob/master/connector/gitlab/gitlab.go:187

one can find 

```
	ident.Name = name
	ident.Username = name
        ident.Email = user.Email
```

probably should be 
```
ident.Username  = user.Username
```

which seems to be incorrect assingment

**Comment by vito** [comment]
@pivotal-jwinters Looks like this is something changed in our fork, do you think it should be changed? (Is it too late? Is this going to break people using GitLab integration?)

**Comment by pivotal-jwinters** [comment]
@vito @pfijalki yeah it should probably be changed to `user.Username`

**Comment by tuapuikia** [comment]
Now I know why it failed when I use gitlab username instead of gitlab user full name.
