### ISSUE TITLE
Possibility of pass the access token on oAuth to the userinfo url?

### ISSUE THREAD

**Issue by TimDiekmann** [concourse/dex#9]
Note: I'm very unfamiliar with Go and I don't know how much effort that would be, but I guess it's just a small change to https://github.com/concourse/dex/blob/2202f4ef4172d234b7c6bbf92ba36c4f4b4d8a76/connector/oauth/oauth.go#L156

I want to use oAuth with [Phabricator as server](https://secure.phabricator.com/book/phabcontrib/article/using_oauthserver/). Acquiring the code and the token seems to work fine. At least I dont get any errors or warnings ;)

However, for retrieving the user info from Phabricator, `/api/user.whoami?access_token=<token>` is required to be called. Is it possible to implement this in the oAuth connector? Currently, the access token is not passed to the server on retreiving user info.

**Comment by vito** [comment]
Hey, sorry but I'm going to close this as we don't really want to be tracking additional work on our fork if it can be avoided. Would you mind opening this [upstream](https://github.com/dexidp/dex)? Thanks!
